name: build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, homelab]
    steps:
    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.5

    - name: checkout code
      uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout 5m
        # latest version is busted: https://github.com/golangci/golangci-lint/issues/3862
        version: v1.52.2

    - name: debug dirs
      run: pwd; ls -R
    - name: build
      run: make build
